apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wfapi.fullname" . }}
  labels:
    {{- include "wfapi.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.wfapi.replicaCount }}
  selector:
    matchLabels:
      {{- include "wfapi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.wfapi.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "wfapi.labels" . | nindent 8 }}
        {{- with .Values.wfapi.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.wfapi.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "wfapi.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.wfapi.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.wfapi.securityContext | nindent 12 }}
          image: "{{ .Values.wfapi.image.repository }}:{{ .Values.wfapi.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.wfapi.image.pullPolicy }}
          env:
            {{- range $key, $val := .Values.wfapi.env }}
            {{- if and $val (ne $val "") }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
            {{- end }}
          envFrom:
            - secretRef:
                name: {{ .Values.envFromSecrets.argoClient }}
          ports:
            - name: http
              containerPort: {{ .Values.wfapi.service.port }}
              protocol: TCP
          startupProbe:
            {{- toYaml .Values.wfapi.startupProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.wfapi.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.wfapi.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.wfapi.resources | nindent 12 }}
          {{- with .Values.wfapi.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.wfapi.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.wfapi.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.wfapi.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.wfapi.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
